version: "2"
services:
  app:
    build: .
    links:
      - db

  db:
    image: mysql

    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /home/hinoki/PycharmProjects/pythonProject1/data:/docker-entrypoint-initdb.d/:ro

      #- ./data:/docker-entrypoint-initdb.d/:ro
