version: "2"
services:
  mysql:
    image: restsql/mysql-sakila:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sakila
      
services:
  jdkSetup:
    image: java:openjdk-9
    command: echo $JAVA_HOME
    ports:
      - 6060:6060






